stages: # define the order and conditions for stages
  - build
  - deploy

jobs:
  include:
    - stage: build # assign a job to a stage
      services: # specify the services for this job
        - docker
      env: # specify the environment variables for this job
        - FOO=foo
        - BAR=bar
      script: 
       - docker build -t hchoi3/demo . 
    - stage: deploy
      services:
        - docker
      env:
        - BAZ=baz
        - QUX=qux
      script: 
       - docker push hchoi3/demo:v1